### PR TITLE
Makes background gradients and textures available to theme

### PR DESCRIPTION
**Pull request by halocline**
#### What does this PR do?

Closes https://github.com/grommet/hpe-design-system/issues/2824 by adding a `backgrounds` theme object with namespaces.

### CODE REVIEW

**Review by taysea — APPROVED** [review]

**Comment by ericsoderberghp** [comment]
I was hoping that these new backgrounds could be used via something like `<Box background="datawave-white-2" />`. But, it looks like this is creating some separate imports.
Also, would it make any sense for any of these to leverage the `{dark: ..., light: ...}` construction to work well with automatic theme mode changes?

**Comment by taysea** [comment]
> I was hoping that these new backgrounds could be used via something like `<Box background="datawave-white-2" />`. But, it looks like this is creating some separate imports. Also, would it make any sense for any of these to leverage the `{dark: ..., light: ...}` construction to work well with automatic theme mode changes?

@halocline can provide more detail, this is the approach we were first aiming to do. There were a couple items re: image positioning that were missing when passing it like this. We went for a first approach of what could be implemented given functionality now, but I think we could (and maybe should) definitely enhance Box to make it work like this.

**Comment by halocline** [comment]
> Also, would it make any sense for any of these to leverage the `{dark: ..., light: ...}` construction to work well with automatic theme mode changes?

We can make that adjustment.

**Comment by halocline** [comment]
> > I was hoping that these new backgrounds could be used via something like `<Box background="datawave-white-2" />`. But, it looks like this is creating some separate imports. Also, would it make any sense for any of these to leverage the `{dark: ..., light: ...}` construction to work well with automatic theme mode changes?
> 
> @halocline can provide more detail, this is the approach we were first aiming to do. There were a couple items re: image positioning that were missing when passing it like this. We went for a first approach of what could be implemented given functionality now, but I think we could (and maybe should) definitely enhance Box to make it work like this.

I agree that `<Box background="datawave-white-2" />` is what we want.

I need to investigate a bit more, but I believe we need to make a couple tweaks to `background.js` to accommodate. There were cases where `background-size` was not being set to `cover` as desired.

Additionally, I wanted to propose supporting `background-clip` to enable some of the typography treatments. Something like:
```
<Box
  background={{
      image: 'datawave-multi-1',
      clip: true,
   }}
>
   <Heading margin="none">Modernize</Heading>
       <Text margin="none" size="xlarge">
           edge to cloud
       </Text>
</Box>
```
and and potentially the ability to rotate the gradients:
```
<Box
     background={{
         image: 'purple-blue-yellow',
         clip: true,
         rotate: 90,
     }}
>
    <Heading margin="none">Modernize</Heading>
        <Text size="xlarge" margin="none">
            edge to cloud
        </Text>
</Box>
```


Lastly, this proposes a new theme property `theme.global.backgrounds`. Are you okay with that direction?

**Comment by ericsoderberghp** [comment]
I'm very supportive of making the necessary changes in grommet to accommodate these things.

**Pull request merged**
